server.port=${PORT:8080}
server.error.include-message=never
server.error.include-binding-errors=never
server.error.include-stacktrace=never
server.error.whitelabel.enabled=false
spring.mvc.log-request-details=false
